version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: logger-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loggerdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
